// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqMz0F68dk8onRxGMj3mcCdSx1P-17pz0',
    appId: '1:506191668527:web:e76b8a040d2c163a262dda',
    messagingSenderId: '506191668527',
    projectId: 'be-ai-mobile',
    authDomain: 'be-ai-mobile.firebaseapp.com',
    storageBucket: 'be-ai-mobile.appspot.com',
    measurementId: 'G-XYXZCNVDMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3czHje9ymEF9b-6HG3-YG05nCF0CGg34',
    appId: '1:506191668527:android:672a0db92a696125262dda',
    messagingSenderId: '506191668527',
    projectId: 'be-ai-mobile',
    storageBucket: 'be-ai-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4jPiCkkXCLXaqbbC0uC4UPJAEvK9VNjw',
    appId: '1:506191668527:ios:81924b9fbc241a6a262dda',
    messagingSenderId: '506191668527',
    projectId: 'be-ai-mobile',
    storageBucket: 'be-ai-mobile.appspot.com',
    iosBundleId: 'com.example.beAiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4jPiCkkXCLXaqbbC0uC4UPJAEvK9VNjw',
    appId: '1:506191668527:ios:81924b9fbc241a6a262dda',
    messagingSenderId: '506191668527',
    projectId: 'be-ai-mobile',
    storageBucket: 'be-ai-mobile.appspot.com',
    iosBundleId: 'com.example.beAiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqMz0F68dk8onRxGMj3mcCdSx1P-17pz0',
    appId: '1:506191668527:web:17116716b6131112262dda',
    messagingSenderId: '506191668527',
    projectId: 'be-ai-mobile',
    authDomain: 'be-ai-mobile.firebaseapp.com',
    storageBucket: 'be-ai-mobile.appspot.com',
    measurementId: 'G-6MQD8FMCPL',
  );
}
